### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by eldyvoon** [ethanselzer/react-touch-position#2]
https://ethanselzer.github.io/react-touch-position/#/image-magnify

I don't see this working.

**Comment by ethanselzer** [comment]
@eldyvoon - Thanks for opening this issue! I think I corrected the problem you identified. Please have a look! Thanks again for bringing this to my attention!

**Comment by ethanselzer** [comment]
@eldyvoon - I'm closing this issue for now. Let me know if you disagree it has been corrected. Thanks!

![react-touch-position](https://cloud.githubusercontent.com/assets/460891/24518163/d85332a0-1535-11e7-9bf4-8e420bad3170.gif)
